src/com/ticketstore/domain/Order.java
package com.ticketstore.domain;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "orderlist")
public class Order {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer orderID;
	@OneToOne(cascade = {CascadeType.REMOVE})
	@JoinColumn(name = "busScheduleID")
	private BusSchedule busSchedule;
	//票的数量
	private int orderTicketNum;
	//订单总价
	private int totalPrice;
	//订单生成日期
	private Date orderDate;
	//所属用户
	@ManyToOne(cascade = {CascadeType.REMOVE})
	@JoinColumn(name = "userID")
	private User user;
	//一个订单只能买一种车程票，但是车票可以买多张
//	@OneToOne
//	@JoinColumn(name = "ticketID")
//	private Ticket ticket;
	//订单状态，是否已付款
	private boolean isPay;
	
	public Integer getOrderID() {
		return orderID;
	}
	public void setOrderID(Integer orderID) {
		this.orderID = orderID;
	}
	public BusSchedule getBusSchedule() {
		return busSchedule;
	}
	public void setBusSchedule(BusSchedule busSchedule) {
		this.busSchedule = busSchedule;
	}
	public int getOrderTicketNum() {
		return orderTicketNum;
	}
	public void setOrderTicketNum(int orderTicketNum) {
		this.orderTicketNum = orderTicketNum;
	}
	public int getTotalPrice() {
		return totalPrice;
	}
	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}
	public Date getOrderDate() {
		return orderDate;
	}
	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
//	public Ticket getTicket() {
//		return ticket;
//	}
//	public void setTicket(Ticket ticket) {
//		this.ticket = ticket;
//	}
	public boolean isPay() {
		return isPay;
	}
	public void setPay(boolean isPay) {
		this.isPay = isPay;
	}
}

WebRoot/header.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <div class="row-fluid">
		<div class="span12">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container-fluid">
					<a class="btn btn-navbar" data-target=".navbar-responsive-collapse" data-toggle="collapse"> </a> 
					<a class="brand" href="index.jsp">售票网</a>
						<div class="nav-collapse collapse navbar-responsive-collapse">
							<ul class="nav">
								<li >
									<a href="index.jsp">首页</a>
								</li>
								<li>
									<a href="/TicketStore/bus_scheduleAction/listAllBusScheduleAction.action">车票预订</a>
								</li>
							</ul>
							<c:choose>
							<c:when test="${sessionScope.LoginedUser == null }">
								<ul class="nav pull-right">
									<li>
										<a href="login.jsp">登录</a>
									</li>
									<li>
										<a href="register.jsp">注册</a>
									</li>
								</ul>
							</c:when>
							<c:otherwise>
								<ul class="nav pull-right">
									<li>
										<a href="/TicketStore/orderAction/listOrderForUserAction.action">欢迎您：${sessionScope.LoginedUser.userName }</a>
									</li>
									<li>
										<a href="/TicketStore/userAction/logoutAction.action">注销</a>
									</li>
								</ul>							
							</c:otherwise>
							</c:choose>
						</div>
					</div>
				</div>
  			</div>
  		</div>
	</div>

WebRoot/index.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html>
  <head>
  	<base href="<%=basePath%>">
    <title>首页 - 售票网</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
        <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
	
	<jsp:include page="header.jsp"></jsp:include>
	<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="tabbable" id="tabs-291660">
				<ul class="nav nav-tabs">
					<li class="active">
						<a data-toggle="tab" href="#panel-564786">最新动态</a>
					</li>
					<li>
						<a data-toggle="tab" href="#panel-188576">常见问题</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="panel-564786">
						<div class="accordion" id="accordion-805271">
							<div class="accordion-group">
								<div class="accordion-heading">
									<a class="accordion-toggle collapsed" data-parent="#accordion-805271" data-toggle="collapse" href="#accordion-element-807389">关于暑假包车优惠有关事宜的公告</a>
								</div>
								<div class="accordion-body collapse" id="accordion-element-807389">
									<div class="accordion-inner">
										<span>为适应旅客需求，充分利用铁路运输能力，2014年3月20日—12月31日期间（9月30日~10月7日除外）始发的部分旅客列车末端空闲卧铺执行优惠票价，即：</span><br /> 
										<span>200公里内硬卧（上、中、下铺）优惠票价按照该次列车对应硬座票价的170%计算，软卧（上、下铺）优惠票价按照该次列车对应硬座票价的270%计算。</span><br /> 
										<span>200公里至400公里间硬卧（上、中、下铺）优惠票价按照该次列车对应硬座票价的158%计算，软卧（上、下铺）优惠票价按照该次列车对应硬座票价的258%计算。</span><br /> 
										<span>已享受半价卧铺票的旅客不再享受以上优惠。</span>
									</div>
								</div>
							</div>
							<div class="accordion-group">
								<div class="accordion-heading">
									<a class="accordion-toggle collapsed" data-parent="#accordion-805271" data-toggle="collapse" href="#accordion-element-631041">包车购票身份核验须知</a>
								</div>
								<div class="accordion-body collapse" id="accordion-element-631041">
									<div class="accordion-inner">
										为了进一步完善包车实名制购票工作，自2014年3月1日起，本网站将对互联网注册用户和常用联系人（乘车人）进行身份信息核验。
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="tab-pane" id="panel-188576">
						<div class="accordion" id="accordion-860798">
							<div class="accordion-group">
								<div class="accordion-heading">
									<a class="accordion-toggle collapsed" data-parent="#accordion-292453" data-toggle="collapse" href="#accordion-element-292453">身份核验结果有哪几种状态？</a>
								</div>
								<div class="collapse" id="accordion-element-292453">
									<div class="accordion-inner">
										对注册用户和常用联系人（乘车人）进行身份信息核验后，持二代居民身份证的有“已通过”“待核验”和“未通过”三种状态，持按规定可使用的有效护照、港澳居民来往内地通行证、台湾居民来往大陆通行证的有“已通过”“请报验”“预通过”和“未通过”四种状态。
									</div>
								</div>
							</div>
						<div class="accordion-group">
							<div class="accordion-heading">
								<a class="accordion-toggle collapsed" data-parent="#accordion-860798" data-toggle="collapse" href="#accordion-element-177969">选<span>扣款成功但购票不成功怎么办？</span></a>
							</div>
							<div class="accordion-body collapse" id="accordion-element-177969">
								<div class="accordion-inner">
									这可能是由于支付时间过长导致的。遇到这一问题后，首先，请不要多次重复购票，以避免多次扣款；其次，请点击附件，下载表格，正确填写相关内容后，将表格以附件方式发送邮件至kyfw@12306.cn，我们将尽快核实后，按银行规定将所扣款项返还至您的银行卡。
								</div>
							</div>
						</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
  </body>
</html>

WebRoot/listInfoForUser.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title>我的订单</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<meta http-equiv="description" content="This is my page">
	<!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

  </head>
  
  <body>
	<jsp:include page="header.jsp"></jsp:include>
	<div class="container-fluid">
		<div class="row-fluid">
		    <p align="center">您的订单</p>
		    <table class="table table-striped">
		    	<thead>
					<tr>
						<th>订单号</th>
						<th>出发地</th>
						<th>目的地</th>
						<th>出发时间</th>
						<th>票价</th>
						<th>订购票数</th>
						<th>订单总价</th>
						<th>下单日期</th>
						<th>已付款</th>
					</tr>
				</thead>
				<tbody>
			    	<s:iterator id="your_order" value="orderList">
			    		<tr>
			    			<td>${your_order.orderID }</td>
			    			<td>${your_order.busSchedule.fromLocation }</td>
			    			<td>${your_order.busSchedule.toLocation }</td>
			    			<td>${your_order.busSchedule.takeOffTime }</td>
			    			<td>${your_order.busSchedule.priceForASeat }</td>
			    			<td>${your_order.orderTicketNum }</td>
			    			<td>${your_order.totalPrice }</td>
			    			<td>${your_order.orderDate }</td>
			    			<td>${your_order.pay }</td>
			    		</tr>
			    	</s:iterator>
		    	</tbody>
		    </table>
		</div>
	</div>
  </body>
</html>

WebRoot/login.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html>
  <head>
  	<base href="<%=basePath%>">
    <title>用户登录   - 售票网</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/mycss.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
        <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
	
	<jsp:include page="header.jsp"></jsp:include>
	<div class="container-fluid">
		<div class="mid_center">
			<s:form cssClass="form-horizontal" method="post" action="/userAction/loginAction.action">
				<fieldset>
					<legend>登录</legend>
			
					<div class="control-group">
				
					<!-- Text input-->
					<label class="control-label" for="input01">账号</label>
					<div class="controls">
						<s:textfield name="user.userName" cssClass="input-middle" placeholder="账号"></s:textfield>
						<p class="help-block">例如：ticketstore@qq.com</p>
					</div>
					</div>
			
					<div class="control-group">
					<!-- Text input-->
					<label class="control-label" for="input01">密码</label>
						<div class="controls">
						<s:password name="user.password" cssClass="input-middle" placeholder="密码"></s:password>
						</div>
					</div>
			
					<div class="control-group">
						<label class="control-label"></label>
						<div class="controls">
							<!-- Multiple Checkboxes -->
							<label class="checkbox">
								<input type="checkbox" value="记住我？">
								记住我？
							</label>
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label"></label>
						<!-- Button -->
						<div class="controls">
							<button class="btn btn-success" style="height:40px;width:217px;font-size:25px;font-weight: bold;" onclick="document.getElementById('login_form').submit()">登录</button>
						</div>
					</div>
				</fieldset>
			</s:form>
  		</div>
	</div>
  </body>
</html>

WebRoot/orderTicket.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title>预订车票</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<meta http-equiv="description" content="This is my page">
	<!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

  </head>
  
  <body>
     <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
	
	<jsp:include page="header.jsp"></jsp:include>
	<div class="container-fluid">
		<div class="row-fluid">
			<p align="center">订票</p>
			<label>您预订的车票</label><br/>
			<s:form action="/orderAction/orderTicketAction.action" method="post">
				<s:textfield name="busScheduleID" cssClass="input-small" readonly="true">班次ID：</s:textfield><br/>
				<br/>
				<label>起始地：${busSchedule.fromLocation }</label><br/>
				<label>目的地：${busSchedule.toLocation }</label><br/>
				<label>发车时间：${busSchedule.takeOffTime }</label><br/>
				<label>车票单价：${busSchedule.priceForASeat }</label><br/>
				<s:textfield name="order.orderTicketNum" cssClass="input-small">预订数量：</s:textfield><br/>
				<br/>
				<button type="submit" class="btn left_bank btn-success">生成订单</button>
			</s:form>
		</div>
	</div>
  </body>
</html>

WebRoot/register.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html>
  <head>
  	<base href="<%=basePath%>">
    <title>用户注册 - 售票网</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/mycss.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
        <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
    <script type="text/javascript">
    	function checkRegister(){
    		var flag = true;
    		var userName = document.getElementById("userName").value;
    		var realName = document.getElementById("realName").value;
    		var telNumber = document.getElementById("telNumber").value;
    		var pass1 = document.getElementById("pass1").value;
    		var pass2 = document.getElementById("pass2").value;
    		if (userName.length == 0){
    			document.getElementsByTagName('p').item(0).innerHTML = '用户名不能为空！！';
    			flag = false;
    		}
    		if (realName.length == 0){
    			document.getElementsByTagName('p').item(1).innerHTML = '真实姓名不能为空！！';
    			flag = false;
    		}
    		if (telNumber.length == 0){
    			document.getElementsByTagName('p').item(2).innerHTML = '联系电话不能为空！！';
    			flag = false;
    		}
    		if (pass1.length == 0){
    			document.getElementsByTagName('p').item(3).innerHTML = '密码不能为空！！';
    			flag = false;
    		}
    		if (pass2.length == 0){
    			document.getElementsByTagName('p').item(4).innerHTML = '密码不能为空！！';
    			flag = false;
    		}
    		if (pass1 != pass2){
    			document.getElementsByTagName('p').item(4).innerHTML = '两次输入密码不一致，请重新输入！！';
    			flag = false;
    		}
    		if (flag == true){
    			document.getElementById('register_form').submit();
    		}
    		return flag;
    	}
    </script>
  </head>
  <body>
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
	
	<div class="container-fluid">
		<jsp:include page="header.jsp"></jsp:include>
		<div class="mid_center">
		<s:form id="register_form" cssClass="form-horizontal" action="/userAction/registerAction.action">
			<fieldset>
		  		<div id="legend" class="">
					<legend class="">注册</legend>
		  		</div>
		
				<div class="control-group">

			  	<!-- Text input-->
					<label class="control-label" for="input01">用户名</label>
			  		<div class="controls">
			  			<s:textfield id="userName" placeholder="用户名" cssClass="input-middle" name="user.userName"></s:textfield>
						<p class="help-block tips" ></p>
			  		</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="input01">真实姓名</label>
					<div class="controls">
			  			<s:textfield id="realName" placeholder="真实姓名" cssClass="input-middle" name="user.realName"></s:textfield>
						<p class="help-block tips"></p>
			  		</div>
				</div>
				
				<div class="control-group">
					<label class="control-label" for="input01">联系电话</label>
					<div class="controls">
			  			<s:textfield id="telNumber" placeholder="联系电话" cssClass="input-middle" name="user.telephoneNum"></s:textfield>
						<p class="help-block tips"></p>
			  		</div>
				</div>

				<div class="control-group">
				<!-- Text input-->
			  	<label class="control-label" for="input01">登录密码</label>
			  	<div class="controls">
			    	<s:password id="pass1" cssClass="input-middle" placeholder="登录密码" name="user.password"></s:password>
					<p class="help-block tips"></p>
			  	</div>
				</div>

				<div class="control-group">
			  	<!-- Text input-->
			  	<label class="control-label" for="input01">确认密码</label>
				<div class="controls">
			  		<s:password id="pass2" cssClass="input-middle" placeholder="确认密码" name="confirmPassword"></s:password>
					<p class="help-block tips"></p>
			  	</div>
				</div>
		

				<div class="control-group">
			  		<label class="control-label"></label>
			  		<div class="controls">
			 		 	<!-- Multiple Checkboxes -->
			  			<label class="checkbox">
						<input value="我已经仔细阅读并接受 车票网注册条款" type="checkbox"/>
						<p>我已经仔细阅读并接受</p>
						<p> 车票网注册条款</p>
		  				</label>
	  				</div>
				</div>

				<div class="control-group">
					<label class="control-label"></label>
				  	<!-- Button -->
				  	<div class="controls">
						<button class="btn btn-success" style="height:40px;width:217px;font-size:25px;font-weight: bold;"onclick="return checkRegister()">注册</button>
			 	 	</div>
				</div>
			</fieldset>
		</s:form>
		</div>
	</div>
  </body>
</html>

WebRoot/ticketBook.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s" %>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>
<!DOCTYPE html>
<html>
  <head>
  	<base href="<%=basePath%>">
    <title>车票预订 - 售票网</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link href="css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
    <link href="css/mycss.css" rel="stylesheet" media="screen">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
        <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
	
	<jsp:include page="header.jsp"></jsp:include>
	<div class="container-fluid">
	<div class="row-fluid">
			<div style="padding-left: 15px">
			<s:form action="/bus_scheduleAction/searchAction.action" method="post" cssClass="form-inline title_center">
				<fieldset>
					<label>出发地</label>
					<s:textfield name="fromLocation" cssClass="input-small" placeholder="出发地"></s:textfield>
					<label class="left_bank">目的地</label>
					<s:textfield name="toLocation" cssClass="input-small" placeholder="目的地"></s:textfield>

					<label class="left_bank">发车时间</label>
					<div class="input-append date" id="datetimepicker" data-date-format="yyyy-mm-dd hh:ii:00">
						<input name="minTakeOffTime" size="100" type="text" placeholder="yyyy-mm-dd hh:ii:ss">
						<span class="add-on"><i class="icon-th"></i></span>
					</div>    
					<label >~</label>
					<div class="input-append date" id="datetimepicker2" data-date-format="yyyy-mm-dd hh:ii:00">
						<input name="maxTakeOffTime" size="100" type="text" placeholder="yyyy-mm-dd hh:ii:ss">
						<span class="add-on"><i class="icon-th"></i></span>
					</div>


					<button type="submit" class="btn left_bank btn-success">查询</button>
				</fieldset>
			</s:form>
			</div>
			
			<div class="row-fluid">
				<div class="span15">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>出发地</th>
								<th>目的地</th>
								<th>出发时间</th>
								<th>票价</th>
								<th>总票数</th>
								<th>剩余票数</th>
								<th>所属承包商</th>
								<th>操作</th>
							</tr>
							</thead>
							<tbody>
								<s:iterator id="bus_schedule" value="busScheduleList">
									<tr>
										<td>${bus_schedule.fromLocation }</td>
										<td>${bus_schedule.toLocation }</td>
										<td>${bus_schedule.takeOffTime }</td>
										<td>${bus_schedule.priceForASeat }</td>
										<td>${bus_schedule.ticketNum }</td>
										<td>${bus_schedule.ticketLeftNum }</td>
										<td>${bus_schedule.contractor.tradeMark }</td>
										<td>
										<a class="btn btn-info" type="button" href="/TicketStore/bus_scheduleAction/findBusScheduleAction.action?busScheduleID=${bus_schedule.busScheduleID }">预订</a>
										</td>
									</tr>
								</s:iterator>
							</tbody>
						</table>
					</div>
				</div>
	</div>
	</div>
	<script type="text/javascript" src="jquery/jquery-1.8.3.min.js" charset="UTF-8"></script>
	<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
	<script type="text/javascript" src="js/locales/bootstrap-datetimepicker.fr.js" charset="UTF-8"></script>
	<script type="text/javascript">
		$('#datetimepicker').datetimepicker('setStartDate', '2012-01-01');
		$('#datetimepicker').datetimepicker();
	
		
		$('#datetimepicker2').datetimepicker('setStartDate', '2012-01-01');
		$('#datetimepicker2').datetimepicker();
	</script>
  </body>
</html>